name: Go CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: go mod init <module-name>
        run: go mod init Hello

      - name: fix dependency
        run: go mod tidy

      - name: Navigate to project directory
        run: cd ${{ github.workspace }}

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Run Go File
        run: go run helloWorld.go
