# This is a basic workflow to help you get started with Actions

name: upload file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   demo-job:
      name: Save output
      steps:
	   - shell: bash
	      run: |
	         expr 1+1 > output.log
	   - name: Upload output file
	      uses: actions/upload-artifact@v3
	      with:
	         name: hari-output-log-file
	         path: output.log
